<a href="https://colab.research.google.com/github/Haris-09/Python-Programming/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
l1 = [1, 2, 3, 4, 5, 6]
l2 = [23, 4, 6, 8, 9, 2]

print(l1/l2)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [12]:
import numpy as np
l1_array = np.array([1,2,3])
print(l1_array)

[1 2 3]


In [13]:
l1_array = np.array(l1)
l2_array = np.array(l2)
print(l1_array/l2_array)

[0.04347826 0.5        0.5        0.5        0.55555556 3.        ]


In [14]:
list2 = [2, 3, 'str1', True]

In [15]:
list2_array = np.array(list2)
print(list2_array)

['2' '3' 'str1' 'True']


In [16]:
l5 = [2, 3, 4]
l6 = [100, 200, 300]
print(l5+l6)

[2, 3, 4, 100, 200, 300]


In [17]:
l7 = np.array(l5)
l8 = np.array(l6)
print(l7+l8)

[102 203 304]


In [18]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [19]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [20]:
weight / height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [21]:
import numpy as np
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [22]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [23]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [24]:
# NumPy arrays: contain only one type will implicitly converts all elements to sting type
np.array([1.0, "is", True])

array(['1.0', 'is', 'True'], dtype='<U32')

In [25]:
d2_list = [[1,2,3],[9,8,7]]
print(d2_list)

[[1, 2, 3], [9, 8, 7]]


In [26]:
d2_array = np.array([[1,2,3],[9,8,7]])
print(d2_array)

[[1 2 3]
 [9 8 7]]


In [27]:
d2_array[:,0]

array([1, 9])

In [28]:
print(d2_array[1,1])
print(d2_array[1][1])

8
8


In [29]:
num_list = [23,5,78,23,90,12]
print(num_list>20)

TypeError: '>' not supported between instances of 'list' and 'int'

In [30]:
new_list = []
for i in num_list:
    if i>20:
      new_list.append(i)
print(new_list)

[23, 78, 23, 90]


In [31]:
num_arryay = np.array(num_list)
print(num_arryay>20)
print(num_arryay[num_arryay>20])
print

[ True False  True  True  True False]
[23 78 23 90]


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [32]:
# lists concatenates and numpy arrays element wise addition
python_list = [1,2,3]
numpy_array = np.array([1,2,3])
print(python_list+python_list)
print(numpy_array+numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [33]:
arr2d = [[1,2,3,4,5,6,7,8],[23,5,7,90,12,23,34,76]]

In [34]:
arr1 = [34,56]
arr2 = [2,3,4]
print(arr1+arr2)

[34, 56, 2, 3, 4]


In [35]:
# Arrays should have same shape
n_arr1 = np.array(arr1)
n_arr2 = np.array(arr2)
print(n_arr1+n_arr2)

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [36]:
arr2d = [[1,2,3,4,5,6,7,8],[23,5,7,90,12,23,34,76]]
numpy_arr2d = np.array(arr2d)
print(numpy_arr2d[:, 1:3])

[[2 3]
 [5 7]]


In [37]:
np_2d = np.array([[1.73,1.68,1.71,1.89,1.79],
                 [65.4,59.2,63.6,88.4,68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [38]:
np_2d.shape

(2, 5)

In [39]:
np_2d = np.array([[1.73,1.68,1.71,1.89,1.79],
                 [65.4,59.2,63.6,88.4,"68.7"]])
np_2d

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [40]:
student1 = np.array([["ali", "sara", "zara"],[2, 12, 3],[23, 34, 90]])
print(student1)

marks_int = []
marks = student1[2]
for mark in marks:
  marks_int.append(int(mark))

print(np.mean(marks_int))
print(np.mean(np.astype(student1[2], int)))
print(np.mean(np.int32(student1[2])))
print(np.mean(student1[2].astype(int)))

[['ali' 'sara' 'zara']
 ['2' '12' '3']
 ['23' '34' '90']]
49.0
49.0
49.0
49.0


In [41]:
data = [3, 7, 5, 12, 8]
print(np.mean(data))
print(np.median(data))
print(f"{np.std(data):.2f}")
print(np.max(data))
print(np.min(data))

7.0
7.0
3.03
12
3


In [42]:
np.random.rand(3,2)

array([[0.51143782, 0.07244413],
       [0.10352722, 0.31073331],
       [0.73021576, 0.73599815]])

In [43]:
num_array = np.array([1, 2, 3, 4, 5])
print(num_array[1])
print(num_array[1:4])
num_array[0:3] = [10,20,30]
print(num_array)

num_list = [1, 2, 3, 4, 5]
print(num_list[1])
print(num_list[1:4])
num_list[0:3] = [10, 20, 30]
print(num_list)

2
[2 3 4]
[10 20 30  4  5]
2
[2, 3, 4]
[10, 20, 30, 4, 5]


In [44]:
# cannot add string to the numpy numeric array
num_array = np.array([1, 2, 3, 4, 5])
num_array[2] = 'three'

ValueError: invalid literal for int() with base 10: 'three'

In [45]:
num_list = [1, 2, 3, 4, 5]
num_list[2] = 'three'
print(num_list)

[1, 2, 'three', 4, 5]
